version: "3"

networks:
  api:

services:
  go_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api_talk
    networks:
    - api
    ports:
    - 8080:8080
    volumes:
    - ./:/app